plugin:
    name: 'geekslab.payments::lang.plugin.name'
    description: 'geekslab.payments::lang.plugin.description'
    author: 'Geeks Lab'
    icon: oc-icon-adjust
    homepage: ''
permissions:
    geekslab_payments_types:
        tab: 'geekslab.payments::lang.plugin.name'
        label: 'geekslab.payments::lang.permissions.types'
